### PR TITLE
Use latest ocean.js

### LINKED ISSUE #897: Add support for latest ocean.js
Ocean.js 0.19.0 has some breaking changes (see https://github.com/oceanprotocol/ocean.js/pull/944)

Tackle that

### PR DESCRIPTION
**Pull request by alexcos20**
Close #897

### CODE REVIEW

**Review by bogdanfazakas — COMMENTED** [review]
Using oceanjs 0.19.0 I'm not able to start any compute job from the market, It always fails on order algorithm (see print screen), Testing with the current market versions works with the same dataset and algorithm combinatio
Screenshot 2021-10-04 at 10 42 33
n

**Comment by alexcos20** [comment]
> Using oceanjs 0.19.0 I'm not able to start any compute job from the market, It always fails on order algorithm (see print screen), Testing with the current market versions works with the same dataset and algorithm combination Screenshot 2021-10-04 at 10 42 33

I'm investigating this

**Comment by alexcos20** [comment]
joust bought a c2d job on https://market-cfdgt8aih-oceanprotocol.vercel.app/asset/did:op:CADfa04c907c1024Ee961BD2bB793Bd017f18F43 , using https://market-cfdgt8aih-oceanprotocol.vercel.app/asset/did:op:B4a9d70739bD74a6Af12313011C953DC44B9c8DA as algo.

Went well

**Comment by jamiehewitt15** [comment]
I also ran a compute job on this branch and got an error, although a different error to @bogdanfazakas. Using [this](https://market-cfdgt8aih-oceanprotocol.vercel.app/asset/did:op:8921f0F2bCE1293772c4F091ebeda4D25eef024a) dataset with [this](https://market-cfdgt8aih-oceanprotocol.vercel.app/asset/did:op:91D1780Ea0c7a450Ed91572b9052B0fFC3171dc8) algorithm.

Screenshot from 2021-10-04 13-09-20



compute error

I'll run a couple more tests.

**Comment by alexcos20** [comment]
looks like we are getting a lot of problems from provider.

**Comment by jamiehewitt15** [comment]
Getting another problem now... When I go to "All datasets and algorithms", then filter to algorithms and sort by relevance, it crashes: 

sort by relevance crash

Click [here](https://market-cfdgt8aih-oceanprotocol.vercel.app/search?page=1&serviceType=algorithm&sortOrder=desc&sort=_score) to replicate.

**Comment by alexcos20** [comment]
> Getting another problem now... When I go to "All datasets and algorithms", then filter to algorithms and sort by relevance, it crashes:
> 
> sort by relevance crash
> 
> Click [here](https://market-cfdgt8aih-oceanprotocol.vercel.app/search?page=1&serviceType=algorithm&sortOrder=desc&sort=_score) to replicate.

this is non related with new ocean.js.

from code I see:
```
<div className={styles.content}>
          <Dotdotdot tagName="p" clamp={3}>
            {removeMarkdown(
              attributes?.additionalInformation?.description.substring(
                0,
                300
              ) || ''
            )}
          </Dotdotdot>
        </div>
```
I'm pretty sure that we have some assets published without description key set.

**Comment by jamiehewitt15** [comment]
@alexcos20 Yeah, you're right. It also crashes on our live site... See [here](https://market.oceanprotocol.com/search?page=1&serviceType=algorithm&sortOrder=desc&sort=_score) when you have Rinkeby selected in the network selector. I'll create a separate issue for that

**Review by bogdanfazakas — APPROVED** [review]
in the end seems that the issues are not related to the oceanjs version and the changes required for this bump are are more likely related to provider. I was able to start the job with the assets mentioned above that were failing earlier

**Review by jamiehewitt15 — APPROVED** [review]
Tested with a couple more assets and it seems to work

**Pull request merged**
