### PR TITLE
More footer data

### PR DESCRIPTION
**Pull request by kremalicious**
- output total datatoken liquidity in footer stats
- add build id to footer

The build id on deploy previews is the branch name, linked to respective branch on GitHub:

Screen Shot 2020-11-08 at 14 42 25

Locally, it will output `dev`, linked to the commit on GitHub:

Screen Shot 2020-11-08 at 14 43 53

All `main` branch builds (which should be the live builds) will output the shortened commit hash, linked to commit on GitHub:

Screen Shot 2020-11-08 at 14 44 58

### CODE REVIEW

**Comment by mihaisc** [comment]
What is the value of the build id for the plain user?

**Comment by kremalicious** [comment]
mainly for us for debugging but for end users it's also a transparency signal making it clear that what is in the repo is also what's deployed.

**Comment by mihaisc** [comment]
fair enough, should we add a tooltip or a label ?

**Comment by kremalicious** [comment]
good idea, gonna add a simple HTML title

**Comment by kremalicious** [comment]
Remaining thing we can only test live is if Vercel actually does a `main` branch build all the time. It seems sometimes it just switches the domain for the preview deployment to live domain, and sometimes not, despite doing a squash commit.

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
