### PR TITLE
V4 barge

### PR DESCRIPTION
**Pull request by rogargon**
This PR tries to address some issues when trying to use the market just over locally deployed infrastructure (aquarius, ganache, contracts, thegraph, provider,...), similar to those described in #1567.

Changes proposed in this PR:
- Example .env to use with barge
- Add local barge to networks-metadata.json
- Use dev config with locally deployed contracts for network 8996
- start-local script triggering local ocean-subgraph codegen

Altogether, they should make it easier to use the market locally. Tested and able to publish both a dataset and an algorithm. I also bought and downloaded the dataset.

### CODE REVIEW

**Comment by kremalicious** [comment]
this affects too much running the app against remote networks, like always adding dev network to network selection at all times. And unnecessary duplication with added scrips which only change 1 line.

So this would need some more thinking and a better strategy, like:

- read out the `chainIdsSupported` & `chainIds` arrays from `.env` vars
- read out subgraph URI for pre-generation from `.env` vars
- then pretty sure we need some signal from user that they want to run against barge, as we need to conditionally load or not load contract artifacts. Ideas welcome

**Comment by htcarr3** [comment]
I'm glad to see someone trying to get some traction on this. The docs don't paint an accurate picture on how to make barge/market stack locally, and has made onboarding our team slow and developing on ocean difficult. There are errors if you don't include an infura project id, errors when trying to connect to local ganache, and various development configs (ocean.ts) are commented out without any mention in the docs. We would be happy to help develop a friendlier local dev environment. Can you help clear up what are the known local development issues?

**Comment by shadmoney** [comment]
> I'm glad to see someone trying to get some traction on this. The docs don't paint an accurate picture on how to make barge/market stack work locally, and has made onboarding our team slow and developing on ocean difficult. There are errors if you don't include an infura project id, errors when trying to connect to local ganache, and various development configs (ocean.ts) are commented out without any mention in the docs. We would be happy to help develop a friendlier local dev environment. Can you help clear up what are the known local development issues?

Agreed on this sentiment, we would also like to contribute back to the documentation on the missing gaps. This will help more teams build on ocean quickly and efficiently.

**Comment by rogargon** [comment]
The same for us, not being able to run the Market on a local Barge was complicating our development efforts. These changes are just a quick and dirty successful test as we have been able to make it work. We will continue elaborating on them, so the tests pass and it integrates smoothly into the main branch. Additionally, we can add a section to the README about the steps to get it working

**Comment by htcarr3** [comment]
> 

Thank you, yes at the very least the README should make it clear that, while barge can be run locally, market does not work with it out of the box. The docs currently read as if it should work out of the box.

**Comment by kremalicious** [comment]
This will be taken over by #1729 and all solutions to this incorporated there

**Pull request closed without merging**
