### PR TITLE
add sample file to edit metadata form

### LINKED ISSUE #386: editMetadata: Allow sample links removal
In the edit metadata screen allow editing sample files. This implies multiple user jobs-to-be-done:

- edit existing sample file URL
- add new sample file URL when none present yet
- remove existing sample file URL

This is a requirement for https://github.com/oceanprotocol/ocean.js/issues/563 & https://github.com/oceanprotocol/ocean.js/pull/598 to be shipped.

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #386  .

Changes proposed in this PR:

- bumps ocean.js to 0.11.4
- bumps react hooks to 0.5.5
- datasset added new input field for sample links on edit metadata form
- allows users to edit, remove, or add sample files to an existing

### CODE REVIEW

**Comment by mihaisc** [comment]
Removing the sample file is not working
image
image

**Comment by bogdanfazakas** [comment]
> Removing the sample file is not working
I tested also and remove it's not working from the preview, i guess that should be ok because locally it works but I'm using local build versions for lib and react from this PR (https://github.com/oceanprotocol/ocean.js/pull/598) in oceanJS that was blocked by this feature and was not merged and released.

**Comment by mihaisc** [comment]
Update ocean.js to 0.11.2 and i think it's good to go

**Comment by bogdanfazakas** [comment]
> Update ocean.js to 0.11.2 and i think it's good to go

I took a look over the failing tests and I think we have to release a new version of the react hooks also, with updated version of oceanjs. I tried this locally and it passes the tests

**Pull request merged**
