### PR TITLE
header space saving & interaction tweaks

### LINKED ISSUE #1544: Mobile user experience for header is bad on small viewports
Trying to press on the profile icon on mobile is an absolute nightmare, I feel like I'm playing a game. I realise that it's not like this on every device so I think we also need to do more testing on other mobile devices - probably we'll find other strange user experiences. 

https://user-images.githubusercontent.com/20739535/175502810-635b3216-7774-47ab-af33-26a5864fa9fb.mp4

Using:
Samsung Galaxy S20 FE
Android 12

### PR DESCRIPTION
**Pull request by kremalicious**
Fixes #1544

* [x] remove network name reveal interaction on small viewports
* [x] increase header button sizes for all viewports for better tap targets
* [x] tweak flex layout
* [x] remove caret from version badge on smaller viewports, consolidate caret styles
* [ ] deal with _Test_ label on network name
* [x] deal with _Reconnecting_ label on account
* [x] fix NFT tooltip icon placement on asset details

### CODE REVIEW

**Comment by kremalicious** [comment]
@jamiehewitt15 please test away on your phone, this was a great baseline. We might not even need to deal with the _Test_ label as I squeezed lots of pixel space out of that header so far

**Review by claudiaHash — APPROVED** [review]
All these changes look good on Galaxy S10+. Can't see the _Test_  label  anymore for network on mobile.

**Comment by jamiehewitt15** [comment]
On my phone, the heading is still split into two lines

**Comment by kremalicious** [comment]
> On my phone, the header is still split into two lines

Thanks! Could you please post a screenshot with wallet connected to one of the main networks?

**Comment by jamiehewitt15** [comment]
Yeah, looks much better when on mainnet, without the "test" label

Screenshot_20220628-100756_MetaMask

**Comment by jamiehewitt15** [comment]
> This should be gone now for you, right?

Yeah the layout jumping has stopped on both mainnet and test nets.

**Pull request merged**
