### PR TITLE
restore error check on custom params inputs

### LINKED ISSUE #1979: Consumer parameters fields redirect to blank page
**Describe the bug**
Consumer parameters fields redirect to blank page. When filling the consumer parameters for algorithm (also for dataset additional information regarding user data that can be specified for dataset publish) at the publishing part (publish/1), it redirects the user to a white page of Ocean Market.

**To Reproduce**
1. Go to `Metadata` step when publishing an algorithm
2. Check that the algorithm has consumer parameters (custom data)
3. Fill one field and click to fill another one

**Expected behavior**
To be able to complete all the fields necessary for custom data

**Screenshots/ Screen recordings**

https://github.com/oceanprotocol/market/assets/50501033/7b1b8992-1528-4209-aeb6-89282eaf4bfe

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1979 .

Changes proposed in this PR:

- restore customer parameter error check

**HOW TO TEST:**

Publish:
- Go to Publish
- Select "Algorith" asset type
- Complete the rest in the form
- Check this "This asset uses algorithm custom parameters"
- Add, test, review custom parameters' fields

Edit:
- Go to an asset with custom parameters you had published
- Click on "Edit"
- Add, remove, test, review custom parameters
- Save changes

### CODE REVIEW

**Comment by mariacarmina** [comment]
I can confirm that the issue is fixed right now, I could add the parameters attached to the algorithm. Thank you @EnzoVezzaro! I'll approve.

**Review by mariacarmina — APPROVED** [review]

**Review by bogdanfazakas — APPROVED** [review]
lgtm

**Comment by LucaMilanese90** [comment]
I noticed this broke the custom provider validation, you could probably just add ` !field.name.endsWith('.providerUrl')` to the checkError function.

**Comment by EnzoVezzaro** [comment]
> I noticed this fix broke the custom provider validation (try to remove the default provider and add a new one and you'll see the app crash), you could probably just add `!field.name.endsWith('.providerUrl')` to the `checkError` function.

Great catch 👍🏽 I created a [PR](https://github.com/oceanprotocol/market/pull/1992) to fix this. Your solution @LucaMilanese90 seems to work, thanks for that.

**Pull request merged**
