### PR TITLE
Show test label only for test networks

### LINKED ISSUE #982: Mainnet networks are shown with Test label
Introduced with #980

Screen Shot 2022-01-11 at 10 02 14

On live, and also now in `v4` branch

### PR DESCRIPTION
**Pull request by claudiaHash**
Fixes #982 .

Changes proposed in this PR:

- check network type and show test label accordingly

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
Is there a working deployment of this branch or does it need to be tested locally?

**Comment by claudiaHash** [comment]
> Is there a working deployment of this branch or does it need to be tested locally?

This has to be tested locally because vercel has some issues and fails to create a deployment preview.

**Review by jamiehewitt15 — CHANGES_REQUESTED** [review]
@claudiaHash I tested it locally and it is fixed for Polygon, which no longer shows the "test" label. However, the Moonriver network is show the "test" label. 

moonriver - test - 2022-01-17_13-11

**Comment by claudiaHash** [comment]
Thanks for testing this, @jamiehewitt15 !  I'm trying to reproduce the issue, because currently seems to work even for Moonriver network.

Screenshot from 2022-01-17 12-59-56

**Comment by jamiehewitt15** [comment]
I just tested it again and it seems to be working fine. I must have done something wrong the first time. Thanks

**Review by jamiehewitt15 — APPROVED** [review]

**Review by bogdanfazakas — APPROVED** [review]
LGMT, tested locally and seems to work as expected now

**Comment by kremalicious** [comment]
trying to trick Vercel again so `main` build succeeds, but Netlify on `main` should just work, we'll see

**Pull request merged**
