### PR TITLE
Reorganize history page

### LINKED ISSUE #374: Reorganize History page
At the moment the history page is a place to put all kinds of lists creating a very busy page, visually, interactively, and performance-wise. Some quick fixes like #351 we can do but we should think about a reorganization of the whole page.

A first goal is to come up with a good way to make it more focused before starting any implementation, some quick suggestions could be, more welcome!:

- split up different lists into different screens
- via sub-menu, or tabs
- reorganize lists across whole app to maybe put them more in context, e.g. does it make sense moving the pool shares to the front page?
- have some lists in some "global" UI, like a button in main menu 

What should be considered:
- performance: adding stuff to front-page has implication on Time to Interaction, which is really important on front-page
- layout shifts: empty/loading tables vs. filled tables create a lot of layout shifts which should mostly be either prevented or made sure they don't affect too much on one screen

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #374 .

Changes proposed in this PR:

- reorganize history page

### CODE REVIEW

**Comment by mihaisc** [comment]
Looks/works nice but the tables need some tweaks. The waves are making part of them hard to read

image

**Comment by mihaisc** [comment]
Dark theme looks better than white theme but i think it's good enough. Only one more issue, if there are no items returned you get this text that blends in the waves

image

**Comment by kremalicious** [comment]
we usually try to put main content on a screen into content boxes, our `Box` style component. For this here it seems we should use the UI pattern already in #376 for the publish form where tab bar and content are visually connected:

Screen Shot 2021-03-11 at 12 42 32

There's also a global background colors change in #376 to separate content & background better but that we do not need to bring over since that requires some drastic changes.

As for mobile, I would suggest a simple overflow pattern for the tabs, like our main menu.

Another thing we need to have is being able to link to respective tabs. But we do not want tab clicking be part of browser history. So not sure we can find a compromise here where tab selection is part of URL but user hitting back button in browser should not make them go through tabs, but really to last page.

**Comment by kremalicious** [comment]
Woah, it looks perfect now and is already a huge usability win for this page 🤩  I would say we can ship that, and figure out improvements when we need them like the linking.

Only interaction improvements I can think of would be to find a way so that not every tab click reloads the data so the box collapse is minimized, e.g. by centralizing data fetching in some parent component but that sounds like a bit too much optimization at this point in time

**Review by kremalicious — APPROVED** [review]

**Pull request merged**
