### PR TITLE
Fix missing pool creation tx

### LINKED ISSUE #1209: pool creation tx are missing from pool transactions lists
Consider this pool which was created by currently connected user:

Screen Shot 2022-03-17 at 14 09 34

And 50 OCEAN were sent into that pool upon creation:
https://rinkeby.etherscan.io/tx/0x9465e0f040323faedfa94ea0e938cab382c9a9ea60c7ba831ef2e868c6c3ee5e

So the pool transactions list at very end should include an entry `Created pool with 50 OCEAN`. This applies to pool transactions list on profile page too. Worth double checking if pool exit tx are missing too

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #1209 .

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
Is there a case where datatoken address differs from one transaction to another?
From what I see it's the same, and we expect to get a different asset for each tx datatoken but instead we get only one:
https://github.com/oceanprotocol/market/blob/v4/src/components/%40shared/PoolTransactions/index.tsx#L183
So there is no `ddoList[1], ddoList[2]` and that's why networkId is set as undefined resulting transaction link to fail.

**Comment by mihaisc** [comment]
In that case it means `getAssetsFromDtList` is failing for some reason.

**Comment by KatunaNorbert** [comment]
The filter it's working, the issue is that we are filtering by the the same id that's we are getting only 1 result. 
But it's not directly related to this PR and saw that it was handled over #1210

**Comment by mihaisc** [comment]
So from what i can see this is working , i have pool create.
image
Is there an issue left regarding this?

**Comment by KatunaNorbert** [comment]
No, all good from my side

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
