### PR TITLE
Update fetch free price

### LINKED ISSUE #605: Update fetch price to include free pricing schema
Update all price fetch mechanisms to include free pricing schema ( e.g. `Asset.tsx`, `subgraph.ts` , price on teaser)

### PR DESCRIPTION
**Pull request by krisliew**
Close #605

Changes proposed in this PR:

- Fetch free pricing asset 

image

Pending:
- [x] Update ocean.js version with this PR https://github.com/oceanprotocol/ocean.js/pull/821 in to pass CI / test check

### CODE REVIEW

**Comment by kremalicious** [comment]
quick UI feedback, current UI has too many 0's and currencies and labels when in reality it just needs one "Free":

Screen Shot 2021-06-08 at 11 33 31

Also the button then can't say "Buy" as the asset is free.

**Comment by krisliew** [comment]
> home page fails to load, am i missing something?

@mihaisc seems like wallet need to be connected first.

**Comment by mihaisc** [comment]
That is not ok, the market need to work without a wallet

**Comment by kremalicious** [comment]
> seems like wallet need to be connected first.

again, not an option. Every user coming first to our app has no wallet connected

**Comment by krisliew** [comment]
@mihaisc @kremalicious Seems like the `dispenser` is not added in the mainnet subgraph which is causing the errors. https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql

**Comment by mihaisc** [comment]
@alexcos20 do we have different versions of subgraph on main and testnets?

**Comment by mihaisc** [comment]
It should be `Free`
image

**Comment by mihaisc** [comment]
i found 2 free assets that you published on rinkeby, can't order any of them. And the button should be `Order` not `Buy`

https://market-qcwavxbd1-oceanprotocol.vercel.app/asset/did:op:8CE4EAF329A6618d554DBc0936791FF0DD5dF5cd
image

**Comment by krisliew** [comment]
@mihaisc ah my bad, for the "buy" button and order it is done at this PR https://github.com/oceanprotocol/market/pull/654 
For the "0 Ocean" at algorithm list, I will update that in a bit.

**Comment by mihaisc** [comment]
I moved that comment here https://github.com/oceanprotocol/market/pull/654 , got a bit confused between them. Think it should have been just one pr.

**Comment by mihaisc** [comment]
> quick UI feedback, current UI has too many 0's and currencies and labels when in reality it just needs one "Free":
> 
> Screen Shot 2021-06-08 at 11 33 31
> 
> Also the button then can't say "Buy" as the asset is free.

ok so it seems this is fixed in the other pr

**Comment by mihaisc** [comment]
I think we can close this since it's merged in the other pr.

**Comment by krisliew** [comment]
> I think we can close this since it's merged in the other pr.

ok sure. I will update the other PR (https://github.com/oceanprotocol/market/pull/654) with the detail in.

**Pull request closed without merging**
