### PR TITLE
Fix consume of FRE assets & improve error handling

### LINKED ISSUE #1936: Issue when buying asset
Buying this : https://market.oceanprotocol.com/asset/did:op:ac85a7dc5e179e428ea56bbfba80625e3526079e041ac2fec763e360256051a3

image

After i hit retry i get to sign twice, all good. The retry button is still active, if i press it again i sign for download, and then i can successfully download.

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #1936 .

Changes proposed in this PR:

- make sure we wait for the approve tx to finish processing
- fix approve and not request token approvals if already approved
- improve error handling for provider errors (Initialise, FileInfo, StartCompute, ... )

Note requires a new version of ocean.js from this PR https://github.com/oceanprotocol/ocean.js/pull/1745

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
https://github.com/oceanprotocol/market/assets/13741335/f4a4dd07-2642-49eb-9b36-1ea0d5280022

It seems the buttons state is not handling the Retry correctly. What I did was:

1) press "Buy"
2) reject the tx from metamask
3) press "Retry", after the tx is successful the button doesn't change state (stays in Retry)
4) press "Retry" again, the file gets downloaded but the button state is wrong

If you refresh the page, the button says "Download" correctly

**Comment by bogdanfazakas** [comment]
> Testing.SM.4.-.Ocean.Market.-.10.July.2023.mp4 
> It seems the button state is not handled correctly. What I did was:
> 
> 1. press "Buy"
> 2. reject the tx from metamask
> 3. press "Retry". Sign the tx, after the tx is successful the button doesn't change state (stays in Retry)
> 4. press "Retry" again, the file gets downloaded but the button state is wrong
> 
> If you refresh the page, the button says "Download" correctly

thanks @EnzoVezzaro , this is an older issue not introduced by the PR will create an issue so we can fix this as well

**Comment by jamiehewitt15** [comment]
Looks good to me. Let's release the updated version of ocean.js so that we can test this fully

**Comment by jamiehewitt15** [comment]
> thanks @EnzoVezzaro , this is an older issue not introduced by the PR will create an issue so we can fix this as well

Yeah we can deal with that ina separate PR

**Comment by bogdanfazakas** [comment]
> Tried to publish and got this error 🤔

Thanks @jamiehewitt15 good catch 👍 , I've added some new try catch blocks and missed one out of scope variable declaration
Fixed it tho 😄 
Screenshot 2023-07-17 at 09 17 41

**Review by jamiehewitt15 — APPROVED** [review]
Yeah, it's working well now

**Pull request merged**
