### PR TITLE
added dark mode toggle button with switch class

### LINKED ISSUE #1418: storybook: needs a theme toggle button
Every UI component needs to be tested against our light and dark theme. And using Storybook UI during the night burns eyes. 

To solve both, in `.storybook/preview.js`:

- figure out how to add e.g. toolbar button which upon click toggles between light & dark
- activating dark mode does:
  - add `dark` class to the iframe `<body />`
  - switch to Storybook dark UI theme
- activating light mode does:
  - remove `dark` class from the iframe `<body />`
  - switch to Storybook light UI theme

Just toggling that `dark` class will make all our rendered components automatically switch their colors too.

For Storybook UI theming:
https://storybook.js.org/docs/react/configure/theming

Adding things to toolbar is straight forward, but most likely we have to create our own local addon: 
https://storybook.js.org/docs/react/essentials/toolbars-and-globals
https://storybook.js.org/docs/react/addons/addon-types#toolbars

There are various dark mode addons out there but this is not what we want, as we just want to toggle a css class.

Bonus would be adding a `prefers-color-scheme` media query and use that to switch dark/light automatically

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1418 

Changes proposed in this PR:

- added dark mode toggle
- adding branding storybook

Current result:

- [x] Toggle button which applies the correct class on the `<body>` under the `<iFrame>`

Screenshot 2022-10-13 at 11 52 36
Screenshot 2022-10-13 at 11 53 11

Working toward: 

- [ ] Storybook branding (fixing logo)

Screenshot 2022-07-18 at 08 58 35

- [X] Change theme programatically (as for now [what's documented](https://storybook.js.org/docs/react/configure/theming) is not working properly)
- [ ] > Bonus would be adding a `prefers-color-scheme` media query and use that to switch dark/light automatically

### CODE REVIEW

**Comment by mihaisc** [comment]
Is this still relevant, are we using storybook?

**Comment by EnzoVezzaro** [comment]
> Is this still relevant, are we using storybook?

yes, we're using storybook with testing-library. And working on it in #1480

**Comment by kremalicious** [comment]
To finalize, remove the custom theme toggle button and use the one injected by `storybook-dark-mode` (the moon), which now toggles the Storybook UI:

Screen Shot 2022-09-28 at 11 32 34

This button then should also toggle the theme in the iFrame and we can remove the custom button we created, this article has all the solutions:
https://davidyeiser.com/tutorials/storybook-react-with-dark-mode#7-connect-the-react-components-to-the-storybook-dark-mode-control

**Comment by EnzoVezzaro** [comment]
> To finalize, remove the custom theme toggle button and use the one injected by `storybook-dark-mode` (the moon)

Added the toggle button and connected to the theme iFrame, but I'm facing a pretty annoying issue with the custom theme values. Basically, custom logo, font, colors, etc are not being picked up by theme provider in `preview.js`. Still not sure why as it was working fine a little while ago, we never changed it since then. 

I try different king of things: update libs, change some setup values, change manually some values on the context itself before going to the provider, but it didn't have any effect on the preview at all. Not sure what else to try, @kremalicious can you please help me out on this? Do you see anything wrong with the setup? According to [this](https://storybook.js.org/docs/react/configure/theming), should be working.

**Comment by mihaisc** [comment]
closing as this appears to be too much work for not much in return

**Pull request closed without merging**
