### PR TITLE
filter ordered assets by service type

### LINKED ISSUE #509: Assets ordered for starting compute jobs show up under Downloads in History
Not sure what the best solution here is but it feels confusing because from user perspective they did not download anything, here the last 2 assets:

Screen Shot 2021-04-14 at 14 36 12

One solution could be to simply hide non-download orders in this list.

### PR DESCRIPTION
**Pull request by claudiaHash**
Fixes #509 .

Changes proposed in this PR:

- filter ordered assets by ddo service type

### CODE REVIEW

**Comment by claudiaHash** [comment]
I think it's working as Mihai proposed, I'm just thinking now about a solution so we don't fetch the did twice.

**Comment by mihaisc** [comment]
we can still see algos, but i think it's ok because you did sort of download them and you have access to download if you want again. So all good 
image

**Comment by mihaisc** [comment]
> I think it's working as Mihai proposed, I'm just thinking now about a solution so we don't fetch the did twice.

Check how i did in compute history   (in the feature/compute branch) . I fetch all the did from the orders and then filter them. and in the row you pass directly the name and did

**Comment by claudiaHash** [comment]
cool, thanks!

**Comment by mihaisc** [comment]
Also please add a loading spinner , like other tabs

**Comment by claudiaHash** [comment]
sure, on it

**Comment by kremalicious** [comment]
the loader for me just comes up briefly, then the empty screen kicks in, and then the list comes in. We need to make sure the loader stays for as long as the list is compiled

**Comment by claudiaHash** [comment]
checking it right now

**Review by kremalicious — APPROVED** [review]
perfect, all good against `main`. Not sure yet if we have to change something over in `feature/compute`, we'll see after merge

**Comment by claudiaHash** [comment]
just checked it over in `feature/compute` and seems to work correctly

**Pull request merged**
