### PR TITLE
Refactoring Market for new Ocean.js build

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Closes: https://github.com/oceanprotocol/market/issues/480

Changes proposed in this PR:
- Removing imports from utils folder

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
This should only be merged at the same time as: https://github.com/oceanprotocol/ocean.js/pull/698

**Comment by mihaisc** [comment]
Tested locally and it seems to work ok , both start and build.

**Comment by kremalicious** [comment]
this now needs a `main` merge and an update to the upcoming ocean.js `v0.13.0`. After that might require some more changes after latest `main` changes

**Comment by mihaisc** [comment]
consumed a file on the deployed instance and it worked

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
