### PR TITLE
Help messages & price display for starting compute job

### LINKED ISSUE #470: help messages & price display for starting compute job
Our existing help messages which we adapt based on existence of a previous order need to be adapted for the compute case where we now have 2 orders (dataset + algo) we have to consider.

Screen Shot 2021-04-01 at 16 54 37

Likewise there should be some output of what user has to spend which most likely correlates with the help text:

112819187-9c761800-9084-11eb-92b9-46f4e18e96d5

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #470 .

Changes proposed in this PR:

- added price info section with all amount ocean to be spend for a specific compute job
- updated help message on compute assets in BuyButton component

### CODE REVIEW

**Comment by kremalicious** [comment]
first find, all the prices in output are different and do not reflect what we show on dataset/algo:

Screen Shot 2021-04-07 at 10 32 23

**Comment by bogdanfazakas** [comment]
> first find, all the prices in output are different and do not reflect what we show on dataset/algo:
> 
> Screen Shot 2021-04-07 at 10 32 23

Hmm good finding, think that's because in compute component we get the price from the graph and send it to the BuyButton component and in AssetSelection we get it from the aquarius

**Comment by mihaisc** [comment]
Fort [this asset](https://market-h5cvr2rjg-oceanprotocol.vercel.app/asset/did:op:8008Ef59A5B79353f15A06BdeB81cEd6c64ff7aC) the algo list fails to load (aquarius query fails). Probably because of this 
image

**Comment by bogdanfazakas** [comment]
> Fort [this asset](https://market-h5cvr2rjg-oceanprotocol.vercel.app/asset/did:op:8008Ef59A5B79353f15A06BdeB81cEd6c64ff7aC) the algo list fails to load (aquarius query fails). Probably because of this
> image

Yeah it was fixed on the compute branch, will merge compute branch in here also

**Comment by kremalicious** [comment]
made price output minimal, I think it is still clear that we add the 2 shown prices together:



for now left the full calculation code commented out, it's handy for debugging.

Except for the algo price differences, the remaining use case is combination of dataset or algo having previous order. In those cases they should be removed from `totalPrice`

**Comment by kremalicious** [comment]
Unknown

Cause I think the timeout displayed in help message does not make sense:

Screen Shot 2021-04-07 at 13 32 00

I bought _Test Algo_ more than 1 day ago so just checking for previous order is not enough, we also need to check if previous order is within the timeout of the algo if I get this right. But we can leave all that to #474

**Comment by mihaisc** [comment]
So the messaging regarding timeout will be handled in another pr or am i misunderstanding?

**Comment by kremalicious** [comment]
with last night's commits this is the current state, could not find a good way to put all that info on screen at once, so moved to tooltip:

Screen Shot 2021-04-08 at 16 04 40

Screen Shot 2021-04-08 at 16 04 52

Also did all this timeout displaying stuff we talked about, and in case of previous orders made sure the price is not added:

Screen Shot 2021-04-08 at 16 05 52

Think the only thing left is that price difference thingy between graph & aquarius but in my testing on Rinkeby, this seemed to have solved itself. Prices seem always correct now so not sure we need to do something here

**Comment by bogdanfazakas** [comment]
i would go for merging this, and for the changes I'm doing with the price for assets from the graph and the previous orders also I'll create a new PR with this subgraph utils.

**Comment by kremalicious** [comment]
good idea with merging, also fine with this.

Suddenly prices are wrong again so we definitely need to get this from graph

Screen Shot 2021-04-08 at 17 09 06

**Review by kremalicious — APPROVED** [review]

**Pull request merged**
