### PR TITLE
Pool statistics graph shows two sets of data when switching tabs

### LINKED ISSUE #691: Pool statistics graph shows two sets of data when switching tabs
## How to reproduce

1. Set the network to Polygon
2. Open the Daily Fishing Effort (01.01.2020) dataset
3. Select the `Pool Tab` - the pool statistics graph looks OK
4. Switch to the `Use Tab` and then return back to the `Pool Tab` - the graph is now broken. It shows two sets of data combined into one

**Normal State**

**Broken State**

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #691.

Changes proposed in this PR:

- Fix pool statistics show the same statistics graphic twice when switching tabs

### CODE REVIEW

**Comment by claudiaHash** [comment]
Tested it with and without a wallet connected and the statistics graphic is displayed correctly in both cases. Looks good to me!

**Review by claudiaHash — APPROVED** [review]

**Comment by kremalicious** [comment]
Just comparing graphs between live and preview and while PR fixes the original issue I find some graphs to be completely different with this preview, while some like DataUnion are the same.

Some differences, do we know why this happens and if the new graphs are the correct ones then?

---

Screen Shot 2021-06-24 at 11 05 50
https://market.oceanprotocol.com/asset/did:op:b07a8bb80242752ce164560ABCb6517DA90a4F65

Screen Shot 2021-06-24 at 11 06 12
https://market-git-feature-issue691-pool-statistics-graph-oceanprotocol.vercel.app/asset/did:op:b07a8bb80242752ce164560ABCb6517DA90a4F65

---

Screen Shot 2021-06-24 at 11 07 52
https://market.oceanprotocol.com/asset/did:op:a2B8b3aC4207CFCCbDe4Ac7fa40214fd00A2BA71

Screen Shot 2021-06-24 at 11 08 17
https://market-git-feature-issue691-pool-statistics-graph-oceanprotocol.vercel.app/asset/did:op:a2B8b3aC4207CFCCbDe4Ac7fa40214fd00A2BA71

**Comment by kremalicious** [comment]
I think in the preview all the data points all stop at Nov. 2020 although there're many more data points in reality

Screen Shot 2021-06-24 at 11 12 39

**Comment by KatunaNorbert** [comment]
Good point, I tested some assets and looked fine, should have tested more

**Comment by KatunaNorbert** [comment]
It should be fine now

**Comment by kremalicious** [comment]
awesome, thanks, indeed all good now. And it felt so nice seeing all this state handling removed initially but I guess now we know why this is all there

**Pull request merged**
