### PR TITLE
Fix edit form validation

### LINKED ISSUE #1365: No validation error message displayed on edit form
No validation error message is displayed in edit form when changing input content, although the `Submit` button remains disabled:

Screenshot from 2022-04-27 13-50-24

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #1365

Changes proposed in this PR:

- Fixing form validation messages and styles for the edit metadata form
- Removing some V3 code that wasn't used anymore

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
Found some issue:

- validation on description doesn't have the correct border color (is not red when invalid as it should)
- validating Sample File breaks the app

https://user-images.githubusercontent.com/13741335/165929718-debc314c-e08b-44a9-aee0-3d9d47b903be.mp4

**Comment by jamiehewitt15** [comment]
@EnzoVezzaro that's interesting, the border colour is red for me:

edit form validation - 2022-04-29_13-48

The file validation works if you use a valid asset URL but seems to break if it's not valid. I'll fix that.

**Comment by EnzoVezzaro** [comment]
> @EnzoVezzaro that's interesting, the border colour is red for me:
> 
> edit form validation - 2022-04-29_13-48
> 
> The file validation works if you use a valid asset URL but seems to break if it's not valid. I'll fix that.

Yeah, sorry. I wasn't clear enough. Basically, on the title input the red border stays invalid even if you're in focus. The description field instead has the border invalid only if you're not in focus. If the description field is invalid and you're in focus on it, it shows the normal color border instead of the red one like in the title.

**Comment by jamiehewitt15** [comment]
> The description field instead has the border invalid only if you're not in focus. If the description field is invalid and you're in focus on it, it shows the normal color border instead of the red one like in the title.

Ok yeah, I see what you mean now. I just checked the publish page on the v4 branch and the same thing is happening there - the border turns black when in focus. Seems that there must be some other issue causing that.

red title black border - 2022-04-29_15-03

**Review by claudiaHash — APPROVED** [review]
lgtm!

**Comment by EnzoVezzaro** [comment]
> > The description field instead has the border invalid only if you're not in focus. If the description field is invalid and you're in focus on it, it shows the normal color border instead of the red one like in the title.
> 
> Ok yeah, I see what you mean now. I just checked the publish page on the v4 branch and the same thing is happening there - the border turns black when in focus. Seems that there must be some other issue causing that.
> 
> red title black border - 2022-04-29_15-03

It's a CSS related issue. It's caused by [this line](https://github.com/oceanprotocol/market/blob/feature/alert-story/src/components/@shared/FormInput/InputElement.module.css#L21:L21). The correct `InputElement_input` class get's applied, but the CSS overrides it.

**Review by EnzoVezzaro — APPROVED** [review]

**Pull request merged**
