### PR TITLE
add fileinfo fetching

### PR DESCRIPTION
**Pull request by mihaisc**
Reintroduce file info fetching from provider. Can be tested on rinkeby

ToDo

- [x] Provider release and deployments are not done

### CODE REVIEW

**Comment by claudiaHash** [comment]
Testing it, I found some disparities against live on:
-  did:op:1D9a0Ad91a5bD3d4091fD474c481A3079A846260, did:op:5CD4756B5980A1877f0191c2f4A4ef6FfB686596 ( different file size)
- did:op:5B7bb7AF87e952D6D13963968078dE7B1bdA1A4e, did:op:5A67ADd7741326368dDE150BC02821E178F6830B(different file size and type)
- did:op:D0d7b9eb435CE2350BFAFa63d3D99860409B699d ( on live there's no file size shown, on this deploy it is)

**Comment by mihaisc** [comment]
testing with live is not that relevant. On live the fetch is removed so basically you are comparing with what is in the ddo. I compared a few and the new values are correct.

**Comment by kremalicious** [comment]
provider `v0.4.12` is deployed in all networks so we can test this again

**Comment by claudiaHash** [comment]
Tested it again and it looks good to me.

**Review by kremalicious — APPROVED** [review]
yup, agree with @claudiaHash, this now is looking good. For some assets it's now even better and gets file sizes where we didn't before

**Pull request merged**
