### PR TITLE
Release candidate 09-01-2023

### LINKED ISSUE #1813: getInitialPaymentCollector failure
Go to any asset and look into the browser console. All of them show:

> `[MetaFull: getInitialPaymentCollector] TypeError: undefined is not an object (evaluating 'new this.web3.eth')`

This was introduced in https://github.com/oceanprotocol/market/pull/1786, which assumes a web3 instance is always available AND which fires before any web3 instance is available even with wallet connected, leading to error.

### LINKED ISSUE #1847: 404 page not working correctly
**Describe the bug**
404 page doesn't seems to work correctly: the dark mode doesn't work.

Link: https://market.oceanprotocol.com/profile/autobotocean.eth/0xEB18BaD7365a40E36A41fB8734eB0B855d13b74F

https://user-images.githubusercontent.com/13741335/211004457-87c81663-5123-4592-a702-f32b9ce36608.mp4

the page scheme color should be dark not light.

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #1813 
Fixes https://github.com/oceanprotocol/market/issues/1831
Fixes https://github.com/oceanprotocol/market/issues/1443
Fixes https://github.com/oceanprotocol/market/issues/1834
Fixes #1847

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
🤔 interesting. After merging #1850, it started failing this test:

Screenshot 2023-01-10 at 07 12 37

but this PR doesn't touch any of that 🤷🏽‍♂️ strange

**Comment by bogdanfazakas** [comment]
> 🤔 interesting. After merging #1850, it started failing this test:
> 
> Screenshot 2023-01-10 at 07 12 37
> 
> but this PR doesn't touch any of that 🤷🏽‍♂️ strange
> 
> UPDATE: it seems related to this [lines](https://github.com/oceanprotocol/market/blob/feature/issue-1724-graphql-onchain-storage-support/src/@utils/ens/index.ts#L2-L3), basically [this server](https://ens-proxy.oceanprotocol.com/api) is down. How can restore it?
> 
> Example, we call [this](https://ens-proxy.oceanprotocol.com/api/address?name=0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6C84e0) but it's broken

yep there is an issue with the ens proxy, similar to docker hub proxy issue from yesterday, I'm on it atm 😃

**Comment by mihaisc** [comment]
ens and docker were fixed, this should be good right?

**Comment by bogdanfazakas** [comment]
> ens and docker were fixed, this should be good right?

yep fixed both

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
