### PR TITLE
fix file object on edit

### LINKED ISSUE #1817: fix `malformed service files, missing transactionId.` after edit
**Describe the bug**
After editing a file with Arweave I get: "malformed service files, missing transactionId." when trying to initiate provider. You can't consume or get the price.

Screenshot 2022-12-05 at 10 42 42

Screenshot 2022-12-05 at 05 45 53

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1817 .

Changes proposed in this PR:

- fix edit file storage type

To test:

- upload a [file on arweave](https://hv4gxzchk24cqfezebn3ujjz6oy2kbtztv5vghn6kpbkjc3vg4rq.arweave.net/PXhr5EdWuCgUmSBbuiU587GlBnmde1MdvlPCpIt1NyM/) (I use this)
- publish that asset in the market
- go to the asset, the price should work and also consume 
- go to edit page of that asset
- change asset to another one in aweave (i might take some time to be indexed by ES) or just save
- in this PR everything should work and should be able to consume the new asset

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
Can you add more details on how to recreate the original error and test this?

**Comment by EnzoVezzaro** [comment]
> Can you add more details on how to recreate the original error and test this?

Sure, I'll add something to the description of the PR and issue.

**Comment by jamiehewitt15** [comment]
I got an error but looks like it is related to the RPC

image

**Comment by jamiehewitt15** [comment]
Actually I'm getting that on every asset.

Click on asset (works initially) -> click refresh -> now broken (404)

**Comment by EnzoVezzaro** [comment]
@jamiehewitt15 Just tested, but the whole flow is working for me:

Publish:
Screenshot 2022-12-05 at 12 04 42

Edit (look file format):
Screenshot 2022-12-05 at 12 06 57

I haven't been to replicate the RPC errors, but it might've been fixed by merging main. After tests are done, please take a look to see if you still have those issues.

**Comment by jamiehewitt15** [comment]
I tried again but got another error when trying to buy the same asset. I'll publish a new asset and try again

image

**Comment by jamiehewitt15** [comment]
I'm also experiencing issues on main at the moment so it's unlikely the above issue is due to this PR.

Got this when trying to publish on main with Mumbai:

image

**Comment by EnzoVezzaro** [comment]
> I'm also experiencing issues on main at the moment so it's unlikely the above issue is due to this PR.
> 
> Got this when trying to publish on main with Mumbai:
> 
> image

Yeah, I don't think it's related to this PR. 

Is strange, I'm not having this issue on this PR (maybe we have diff configurations on it, I'm using Alchemy), but I don't think is related.

**Comment by EnzoVezzaro** [comment]
@jamiehewitt15 can you please check if you still have the same issue now 👍🏽

**Comment by jamiehewitt15** [comment]
> @jamiehewitt15 can you please check if you still have the same issue now 👍🏽

Yeah, I'm still getting the transaction under-priced error although that is something separate to this PR (https://github.com/oceanprotocol/ocean.js/issues/1661). Only way I have round that for now is manually setting the gas price much higher. When I do that, this works fine without any errors

**Review by jamiehewitt15 — APPROVED** [review]

**Comment by EnzoVezzaro** [comment]
> 

ok, thanks. Not really what we're trying to fix here, but I got you. I move this request to #1724 in order to move on with this PR, since it might blocked users from consuming assets.

**Review by bogdanfazakas — APPROVED** [review]

**Pull request merged**
