### PR TITLE
Walletconnect fix for polygon

### LINKED ISSUE #1545: Wallet balance not being fetched when using wallet connect
Cannot add liquidity/trade on mobile. 
Even if I have funds In my metamask account: mOcean and MATIC and a connection via WalletConnect, on the ocean market the wallet balance is not correctly fetched and I cannot do basically anything. Please see the screenshots: 

289280548_537528818068598_7730857693071466717_n
289333194_577349857366879_1858074185413467295_n
289589030_1027360548173831_3861162979188949792_n

OS: Android 12.0.0.134

### PR DESCRIPTION
**Pull request by mihaisc**
Fix #1545

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
Unfortunately I'm still experiencing this issue. 

In the market with metamask connected:
IMG_6235

This is metamask:
IMG_6236

**Comment by mihaisc** [comment]
Only care about polygon. Yes stuff will not automatically change when switching network or account, you need to do a manual refresh.

**Comment by kremalicious** [comment]
Works! Using Rainbow wallet on same device, which connects through walletconnect. On live I get `NaN`, with this PR I get a a balance:

image

**Review by kremalicious — APPROVED** [review]

**Comment by kremalicious** [comment]
> Unfortunately I'm still experiencing this issue.

You are connected to Mumbai, but fix is for Polygon main (`137`). But most likely we want this fix on Mumbai too if it just involves making WalletConnect use the public RPCs. Mumbai would be https://rpc-mumbai.matic.today/ as per https://docs.polygon.technology//docs/develop/network-details/network/

**Review by claudiaHash — APPROVED** [review]

**Comment by EnzoVezzaro** [comment]
> > Unfortunately I'm still experiencing this issue.
> 
> You are connected to Mumbai, but fix is for Polygon main (`137`). But most likely we want this fix on Mumbai too if it just involves making WalletConnect use the public RPCs? Mumbai would be https://rpc-mumbai.matic.today/ as per https://docs.polygon.technology//docs/develop/network-details/network/

Yes exactly, this is more related to Mumbai. Polygon works as expected, but I agree we should have Mumbai working too.

**Comment by mihaisc** [comment]
Did a quick push for mumbai

**Pull request merged**
