### PR TITLE
Showing hosting type in File Info

### LINKED ISSUE #1834: Add hosting info to Asset Details
With https://github.com/oceanprotocol/provider/pull/584, we are going to have filetype available when calling provider.FileInfoEndpoint, so we can add it to asset details and make it visible for all users

TBD: pictures or text

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #1834

Changes proposed in this PR:

- Showing hosting type in File Info

image

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
LGTM, but SM might need a bit of help 

Screenshot 2023-01-05 at 09 21 54

example [here](https://market-bc2exwtlf-oceanprotocol.vercel.app/asset/did:op:28575e03eaa98c13a8807e9b464fa46ac2957b09256a7d271fc886fb39dd9f5a)

**Review by EnzoVezzaro — APPROVED** [review]
Approved, but we need a little change for `smartcontract`

**Comment by jamiehewitt15** [comment]
> LGTM, but SM might need a bit of help
> 
> Screenshot 2023-01-05 at 09 21 54
> 
> example [here](https://market-bc2exwtlf-oceanprotocol.vercel.app/asset/did:op:28575e03eaa98c13a8807e9b464fa46ac2957b09256a7d271fc886fb39dd9f5a)

Yeah, good spot. Thanks for testing that

**Comment by jamiehewitt15** [comment]
> Approved, but we need a little change for `smartcontract`

I've changed it so that smart contract is written across two lines:

image

**Pull request merged**
