### PR TITLE
Use subgraph enums

### LINKED ISSUE #1040: Use subgraph enums when available
We should use the enums defined in the subgraph.
For example [here ](https://github.com/oceanprotocol/market/blob/2fb7ed35167abd9bc836d7a2857a4b95be63b1a0/src/components/Asset/AssetContent/EditHistory.tsx#L33) we can use 
```
export enum NftUpdateType {
  METADATA_CREATED = "METADATA_CREATED",
  METADATA_UPDATED = "METADATA_UPDATED",
  STATE_UPDATED = "STATE_UPDATED",
  TOKENURI_UPDATED = "TOKENURI_UPDATED",
}
```

### PR DESCRIPTION
**Pull request by KatunaNorbert**
Fixes #1040.

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
I get the following error when importing the enums from `globalTypes.d.ts`. Any ideas why it say that it can't be found?
Screenshot 2022-02-22 at 14 40 22

**Comment by mihaisc** [comment]
it seems there are some issue when generating the types, some queries are outdated, maybe because of that. Does it generate that type locally?

**Comment by KatunaNorbert** [comment]
Yes, it generates it, I removed the file and it got regenerated.

**Comment by mihaisc** [comment]
It seems to be another webpack issue, took a quick look didn't figure it out.

**Pull request closed without merging**
