### PR TITLE
Highlights and clear button on edit UI

### LINKED ISSUE #1244: Edit UI
It works, but it could be better. Biggest issues to solve:

- mix of form elements where some are prefilled and some are not making it hard to know which fields will be edited or cleared
- How to clear fields
- ...

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1244 .

Changes proposed in this PR:

- border outline when an input has changes
- added "search" type on text inputs for clear button support

Current (no feedback): 

Screenshot 2022-09-08 at 08 30 31

PR changes: 

No change:
Screenshot 2022-09-08 at 08 32 05

With change:
Screenshot 2022-09-08 at 08 33 18

The clear "X" button shows up on hover.

WIP: 

- [X] testing outline in edit form
- [x] waiting for #1655 to be merged

### CODE REVIEW

**Comment by mihaisc** [comment]
what is the status of this ? the pr mentioned as required was merged.

**Comment by EnzoVezzaro** [comment]
ready for review @jamiehewitt15 @bogdanfazakas

**Comment by jamiehewitt15** [comment]
I don't understand why the border colour changes to red? To me it looks like I have entered some invalid input. I feel like green would be a better choice?

**Comment by kremalicious** [comment]
> added "search" type on text inputs for clear button support

This will only work in webkit & blink. And it's semantically completely wrong. You also used a `-webkit-` prefix where there should be no prefix usage at all. If you want a clear button in all browsers you actually have to build it for all browsers.

**Comment by mihaisc** [comment]
closing this, minor improvement, taking too much time

**Pull request closed without merging**
