### PR TITLE
fix compute history duplication

### PR DESCRIPTION
**Pull request by mihaisc**
Check the provider compute address to avoid duplication

### CODE REVIEW

**Comment by mihaisc** [comment]
Not sure why this is happening. Deleted `node_modules` locally and did a `npm ci` and `npm run build`, all good.

**Comment by mihaisc** [comment]
All good now

**Comment by kremalicious** [comment]
alright! Way less items now for me in the list. Still get this console error but looks like we can ignore that?

Screen Shot 2021-04-16 at 14 20 53

**Review by kremalicious — APPROVED** [review]

**Comment by mihaisc** [comment]
The error is ok. The provider doesn't exist anymore.

**Pull request merged**
