### PR TITLE
remove amm code cleanup

### LINKED ISSUE #1607: Remove AMM pools functionality
As we are moving away from the dynamic pricing schema, we need to remove everything POOL related.

- [x] #1614 Remove AMM related code (UI)
- [x] #1614 Remove AMM related code (cleanup)
- [x] #1614 Remove tests
- [x] #1610 Update READMEs (docs)

### PR DESCRIPTION
**Pull request by EnzoVezzaro**
- Fixes #1607 

Changes proposed in this PR:

- cleanup amm code

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
@AnaLoznianu I have a question regarding assets with dynamic price. Are we supporting them after removing the AMM functionalities? If we're not, what should we display on these assets? what should expect a user accessing an asset with dynamic pricing after removing AMM?

If I remove all the code related to pools, these won't work anymore. The same for the compute functionalities which are using the pools too, but I guess bogdan is working on it.

**Comment by AnaLoznianu** [comment]
We should filter out all POOL assets. Cause then we have these issues on how to display them, what to add there, and so on. Let's remove them completely

**Comment by kremalicious** [comment]
I do not get the difference between this PR and #1614 so will point this one against the other one. As of right now, both are huge impossible to review PRs and we said we only want one of those.

**Comment by EnzoVezzaro** [comment]
> I do not get the difference between this PR and #1614 so will point this one against the other one. As of right now, both are huge impossible to review PRs and we said we only want one of those.

This PR follows the other PR #1614 because this will be more focused on removing all the leftover code related to AMM once we have removed it from everywhere. We can remove it if it's confusing.

**Comment by kremalicious** [comment]
We said to work in PRs against the branch of #1614 so that PRs become manageable again. 2 PRs with almost the same changeset against `main` are impossible to review. Before I changed the base branch of this PR, it was having almost the same 3000+ lines of code changed. Now here it's 57 and it can actually be reviewed.

It's up to you how you want to handle it. If you only push everything into #1614 it won't be fully code reviewed (which might be fine as we are removing things) but only the functionality in the final preview will be reviewed. Not preferring anything, just pointing out these were the 2 workflows, and we didn't want t workflow where multiple PRs have all the same changeset

**Comment by EnzoVezzaro** [comment]
> We said to work in PRs against the branch of #1614 so that PRs become manageable again. 2 PRs with almost the same changeset against `main` are impossible to review. Before I changed the base branch of this PR, it was having almost the same 3000+ lines of code changed. Now here it's 57 and it can actually be reviewed.
> 
> It's up to you how you want to handle it. If you only push everything into #1614 it won't be fully code reviewed (which might be fine as we are removing things) but only the functionality in the final preview will be reviewed. Not preferring anything, just pointing out these were the 2 workflows, and we didn't want workflow where multiple PRs have all the same changeset

Got it. Ok, I'll move this single commit to #1614 to close this 👍🏽

**Pull request closed without merging**
