### PR TITLE
Update compute history

### LINKED ISSUE #853: Update compute history(C2D breaking changes)
The changes are done after https://github.com/oceanprotocol/ocean.js/pull/983

Taking in consideration the changes in the pr the flow will change . We get the list of results (filename and size) and when we click to download then we need to sign.
Also we will have an `expireTimestamp` that we need to display. This represents how long the results will be kept.

More details on the flow : https://github.com/oceanprotocol/ocean.js/pull/983#issuecomment-927833354

### PR DESCRIPTION
**Pull request by claudiaHash**
Fixes #853 .

Changes proposed in this PR:

- used `status` function without signing it, removed 'Get Results' button
- used `getResults` function signing for each result file

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
Not sure if this is ready for review yet? All the tests are failing

**Comment by claudiaHash** [comment]
> Not sure if this is ready for review yet? All the tests are failing

You're right. Converted it into draft until the `CredentialType` import is resolved

**Review by jamiehewitt15 — APPROVED** [review]
I've looked over the code and it looks fine. The deployment has failed though, so can't check the preview

**Comment by claudiaHash** [comment]
> The deployment has failed though, so can't check the preview

Thanks, @jamiehewitt15 for checking it. Yes, seems to have a problem with the next.js. @mihaisc when you have some time could you please give me some insight of how this can be fixed, is the same problem like in the publishers with most sales PR

**Comment by mihaisc** [comment]
Only issue is that you don't get a proper pointer when you hover over the link , it's not the hand thingy
image

**Review by mihaisc — APPROVED** [review]
DO NOT MERGE !!!!! I will merge it after we deploy the remaining components on main c2d

**Pull request merged**
