### PR TITLE
Account history published page

### LINKED ISSUE #710: Account page - Published
image

Same filters/sort as in search component (maybe we can reuse that) .Show assets from selected chains.

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #710  .

Changes proposed in this PR:

- adds filter by asset type (dataset and algorithms) on published section from account's history page

### CODE REVIEW

**Review by claudiaHash — APPROVED** [review]

**Comment by KatunaNorbert** [comment]
It's working well. I think a loading icon while fetching data when switching between asset type would make the user experience better, like we have on search screen.

**Comment by jamiehewitt15** [comment]
> It's working well. I think a loading icon while fetching data when switching between asset type would make the user experience better, like we have on search screen.

Yeah, I agree, this would be a good addition. It loaded quite slowly when I tested it

**Comment by bogdanfazakas** [comment]
> It's working well. I think a loading icon while fetching data when switching between asset type would make the user experience better, like we have on search screen.

yep good find, loading was displayed only the first time accessing the page, going to change that to every time the data is fetched from aqua

**Comment by jamiehewitt15** [comment]
The loading spinner is good now.

I noticed another small part of the user experience issue that could be improved. When I clicked on the "algorithms" filter (from an account that hasn't published any algorithms) both filters disappeared. When a user has no results to display, neither filter is visible. This creates an odd user experience because my first instinct after clicking the "algorithms" filter was to remove the filter so I could see the datasets I had published from that account.

publish history filters

I would suggest it would be better to keep both filters visible even if there aren't any results to display.

**Review by jamiehewitt15 — APPROVED** [review]
Works great now. Thanks for making the changes

**Comment by bogdanfazakas** [comment]
> Works great now. Thanks for making the changes

Thanks thanks for pointing out the strange behaviour i've missed.

**Pull request merged**
