### PR TITLE
Add symbol for fixed rate exchange

### LINKED ISSUE #833: Token symbols are gone from non-pool assets prices
No token symbols beside the price anywhere, also not on asset details page:

Screen Shot 2021-09-02 at 13 20 13

Screen Shot 2021-09-02 at 13 21 23

Like https://market.oceanprotocol.com/asset/did:op:3a8D5249F74Dd1B61517DFCf5e5facaE38988943

Seems to be happening for all networks, here mixed in ETH Mainet. And looks like it's happening on all assets which are NOT a pool:

Screen Shot 2021-09-02 at 13 25 39

### PR DESCRIPTION
**Pull request by mihaisc**
Closes #833

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
Screenshot 2021-09-02 at 16 48 01

Still no symbol inside the consume components

**Review by kremalicious — APPROVED** [review]
Nice! Working for me in both places now. Lost track of all the queries in that massive `subgraph.ts`, I guess we catched all the recent token symbol changes in there

**Comment by mihaisc** [comment]
one more needed, push incoming

**Comment by mihaisc** [comment]
Updated symbol in swap as well, it was crashing before.

**Review by KatunaNorbert — APPROVED** [review]
Looks good!

**Pull request merged**
