### PR TITLE
Fix infinite loading on file info

### LINKED ISSUE #1938: File download fails
downloading this https://market.oceanprotocol.com/asset/did:op:8de687b14e5181c160a8ab602038f16ddc6557ed3ab494d4bc488d221686164d

returns a json with `{"error":{}}`

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #1938 .

Changes proposed in this PR:

- fixes infinite file loading
- updates provider error handling 

NOTE: requires ocean.js lib 3.1.3 (PR uses pre release ocean.js lib 3.1.3-next.1)
test asset: https://market-git-fix-infinite-file-error-handling-oceanprotocol.vercel.app/asset/did:op:8de687b14e5181c160a8ab602038f16ddc6557ed3ab494d4bc488d221686164d

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
I opened up the test asset page and it's failing to load the price, just seems to be continuously loading. Is this due to the ocean.js version bump that's required?

image

**Comment by bogdanfazakas** [comment]
> I opened up the test asset page and it's failing to load the price, just seems to be continuously loading. Is this due to the ocean.js version bump that's required?
>

no it should not be related to ocean.js update, but the asset above requires about 1 min wait time untill the fileInfo request fails due to bag gateway, see print screen attached

Screenshot 2023-10-13 at 11 09 09

**Comment by AnaLoznianu** [comment]
I tested it out a bit and I've seen the errors displayed, but the spinner is still loading.

**Comment by AnaLoznianu** [comment]
Noup, I was wrong. Waited a bit longer and I the spinner stoped and another error displayed

**Review by AnaLoznianu — APPROVED** [review]

**Comment by mihaisc** [comment]
good to go? i see it was approved

**Comment by bogdanfazakas** [comment]
> good to go? i see it was approved

yes but Ana is not a code owner so i should have bypassed the protections to merge it 😄

**Pull request merged**
