### PR TITLE
Web3/Ocean splitup + full Polygon/Matic support

### LINKED ISSUE #145: OCEAN user balance is null randomly
Happens a lot on Rinkeby. Ran into that on the Cobra Capital asset during the demo:

Screen Shot 2020-10-27 at 16 22 27

### LINKED ISSUE #401: When connected to unsupported network the market freezes
If you have metamask connected to the market and you switch to an unsupported network the market UI freezes and you need to close the tab.

Quick suggestion : ignore the network switch in `NetworkMonitor` if the network id is not supported , not sure this is enough

### LINKED ISSUE #413: Add polygon network/explorer to transaction links component
After adding liquidity to a pool the transaction link is incorrect 

https://polygon.etherscan.io//tx/0x8d9e5bc7e7f8e049d62c252bc22dca531a040acfa73b626a7d9fdf6f6529a207

Should be 

https://explorer-mainnet.maticvigil.com/tx/0x8d9e5bc7e7f8e049d62c252bc22dca531a040acfa73b626a7d9fdf6f6529a207/token-transfers

The same is for all the tx links (pool, datatoken, etc..)

### LINKED ISSUE #418: Incorrect token displayed in wallet
On polygon network in the wallet we show eth instead of matic.

image

### PR DESCRIPTION
**Pull request by kremalicious**
In essence: new `useWeb3()` & `useOcean()` maintained in `market` + all the changes from #406 for Polygon/Matic support.

### Polygon/Matic support

- closes https://github.com/oceanprotocol/multi-repo-issue/issues/82
- fixes #418
- fixes #413

Screen Shot 2021-03-16 at 16 07 59

Screen Shot 2021-03-16 at 19 26 01

### Web3/Ocean split-up

* new `Web3Provider`/`useWeb3()` wrapping the app
  * handling web3 connection with web3modal as before
  * handles user account/network changes
  * exposes network metadata from `https://chainid.network`, and constructs a network display name
* move over `OceanProvider`/`useOcean()` from  `react`, highly reduce what it does: 
  * central place for setting, holding, and changing endpoint configs based on `networkId`
  * hold the Ocean-specific `Account` object needed in some places
  * hold the Ocean-specific user balance (this one could be moved to `Web3Provider` but getting ERC-20 token balances without the helper in ocean.js is cumbersome)
  * change all the data logic flow, everything simply changes based on `accountId` & `networkId` from `Web3Provider`
* between both providers, highly optimized data flow to make sure only necessary RPC and Ocean component endpoint calls are made
  * makes network switching crazy fast and more reliable, with way less memory usage
  * fixes many issues randomly popping up caused by too many RPC calls, takes load from all Ocean component endpoints
  * in some cases, especially in test networks, endpoint calls should be down by 66%, app was repeating many of them 3 times
  * verifiable by looking at the highly reduced amount of browser console messages in debug mode
  * fixes #145 for real without workarounds
  * seems to also fix #401
  * truly decouples user wallet network from ocean endpoints, allowing new UI functionality
  * prototype buttons for endpoint switching independent of user wallet network, for verifying #432
* split-up should make finding a solution for unblocking #361 easier
* new `useAccountPurgatory()` hook
* port over all existing hooks as is, including `useCompute()`, which we should then use for #343 to keep pattern consistent
* remove `useMetadata()` hook, replace with direct DDO value access
* kick out `NetworkMonitor`, functionality is integrated in new `Web3Provider`
* completely remove `@oceanprotocol/react` dependency
* because of code removal and refactoring fixes a bunch of CodeClimate issues along the way

includes learnings from https://github.com/oceanprotocol/react/pull/255 and the [redacted] frontend

Touches almost everything so terrible to review, new magic is happening mainly in:

- `Web3Provider`/`useWeb3()`: https://github.com/oceanprotocol/market/pull/433/files#diff-e44ed1e725b9c26ecad28498d80d998baff95ce5a5527ba88fd6bdb8759057ed
- `OceanProvider`/`useOcean()`: https://github.com/oceanprotocol/market/pull/433/files#diff-63869f26cd5f7eb06fcbaf70892ac8e5e0c018adebaa7b7ebd30650d069b7332

Resulting in nice clean logging in debug mode:

Screen Shot 2021-03-12 at 12 22 23

### CODE REVIEW

**Comment by kremalicious** [comment]
Some findings to figure out how to deal with the `react` repo

- moving over `OceanProvider` right now implies moving over all hooks, because they itself [call `useOcean`](https://github.com/oceanprotocol/react/blob/main/src/hooks/usePublish/usePublish.ts#L28), leading to drastic code base changes for all functionality
- if we do that then there's not much need for the `react` repo at all
- alternative compromise would be to make all hooks over in `react` accept the values exposed by `useOcean` as props

But if we want to minimize the refactor in this repo and for forks:
- we could go back to original idea and leave the `OceanProvider` over there in its new minimal form:
  - exposing `ocean`, `balance` and purgatory info, reacting to web3 account  changes 
  - accepting `web3Provider`, `accountId`, `networkId` as a prop
- would allow easier migration path for users of `react` and `market` forks

In both cases, leave the web3 handling to the client apps. As for this PR this means continuing on the consolidation of all web3-related stuff into one `Web3Provider/useWeb3`

**Comment by kremalicious** [comment]
I'm just not sure deprecating `react` repo is best way because it increases entry barrier to build an app with ocean. Cause this is what moving all the hooks implies to me, not sure we can handle maintenance of `react` repo if we do not use it ourselves.

Fully agree our own maintenance would be greatly reduced by moving everything.  But the hooks do a bunch of more stuff than being simple helper methods, like the feedback & loading states which we would have to rebuild in each component if we limit them to pure helper methods. So would probably move the hooks as is anyway. This would then mean we will direct people to copy out the respective hooks from `market` into their apps which is of course not as convenient as getting it from npm package.

Removed `useMetadata` already, no use in it. Will first try to get `Web3Provider/OceanProvider` to play nice in this repo before moving on to deal with rest of hooks so still plenty of time to decide what to do with the react repo

**Comment by mihaisc** [comment]
Well, i always said to keep the react hooks. They don't need a lot of maintenance and we can keep them as they are now. They represent the basic usage of our tech. In the market we need more customization, because the market is our interpretation of the tech, it's not the only way.
So :
- move what we need to market  (indeed it's a bit more that i suggested but not that much, we can work on this branch in parallel,  like we do with compute)
- we keep the react hooks as they are now and we fix the example. There is no need to change them after, only update ocean js lib (we can configure dependabot for that) 

Considering the overhead that the react hooks generate now, decoupling the repos and supporting them separately will take less time overall.

**Comment by kremalicious** [comment]
and just like that we are finally able to do stuff like this, quick prototype for verifying changes work for solving #432 in the end:

https://user-images.githubusercontent.com/90316/110710611-77695480-81fe-11eb-99d3-056dc2c2ee5c.mov

**Comment by kremalicious** [comment]
nice, also verified our new recently optimized `Wallet` component was created flexible enough so that this combination now just works through UI button network switching:

Screen Shot 2021-03-11 at 17 30 57

**Review by mihaisc — APPROVED** [review]

**Pull request merged**
